### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by daviidmart** [kyu-suke/ming_cute_icons#1]
Update icons please

**Comment by daviidmart** [comment]
Can you add me as collaborator? I make the changes for you

**Comment by kyu-suke** [comment]
Sorry for the late reply, I have published a version (0.0.2) with v2.87 of MingCute applied.
Thanks for the issue.

**Comment by daviidmart** [comment]
> Sorry for the late reply, I have published a version (0.0.2) with v2.87 of MingCute applied. Thanks for the issue.

Thanks 👏
