### ISSUE TITLE
2.95

### ISSUE THREAD

**Issue by MahanRahmati** [kyu-suke/ming_cute_icons#4]
Hi. Thanks for your work.
Version [2.95](https://github.com/Richard9394/MingCute/releases/tag/v2.95) is already out, can you update the package?

**Comment by kyu-suke** [comment]
@MahanRahmati 
Thank you for your issue. I'll respond right away.

**Comment by kyu-suke** [comment]
@MahanRahmati 
Hi! I have released version 0.0.6 to pub.dev which is applied version 2.95.
Thanks.

**Comment by MahanRahmati** [comment]
Thanks! 🙏
